# Generated by Django 4.0.2 on 2022-04-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('uploader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstApp.users')),
            ],
        ),
    ]
