# Generated by Django 4.0.2 on 2022-04-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/results'),
        ),
        migrations.CreateModel(
            name='Photo_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=50)),
                ('object_count', models.IntegerField()),
                ('photo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstApp.photo')),
            ],
        ),
    ]
