# Generated by Django 4.0.2 on 2022-04-03 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_alter_photo_image_photo_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Image', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo_details',
            name='object_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo_details',
            name='object_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo_details',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.photo'),
        ),
    ]
