# Generated by Django 4.0.2 on 2022-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_photo_name_photo_upload_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='photo_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/results'),
        ),
        migrations.AddField(
            model_name='photo_details',
            name='name',
            field=models.CharField(default='Image', max_length=100),
        ),
        migrations.AddField(
            model_name='photo_details',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
