# Generated by Django 4.0.2 on 2022-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_remove_photo_image_remove_photo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/results')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo_details',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo_details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo_details',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Image', max_length=100),
        ),
    ]
