# Generated by Django 4.0.2 on 2022-04-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_photo_history_remove_photo_details_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_history',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.photo'),
        ),
        migrations.AlterField(
            model_name='photo_details',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.photo_history'),
        ),
    ]
